#spring.application.name =cloud-config-client
#server.port=8080
#
student:
  name: Sachin-Dev
#student.rollNo=1234
#student.email=sachin@gmail.com
#student.phone=123456789

spring:
  cloud:
    gateway:
      routes:
        - id: image-route
          uri: lb://springboot3-image-service/
          predicates:
            - Path=/v1/image/**
          filters:
            - StripPrefix=2
        - id: gallery-route
          uri: lb://springboot3-gallery-service/
          predicates:
            - Path=/v1/gallery/**
          filters:
            - StripPrefix=2
