
spring:
  application:
    name: springboot3-gallery-service
  profiles:
    active: "common,dev"
  config:
    import: optional:configserver:http://localhost:8800
  cloud:
    config:
      username: goota
      password: 123456


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      #      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8899/eureka}
      defaultZone: http://localhost:8899/eureka