# swagger-ui custom path
springdoc:
  packagesToScan: lungtungxeng.springboot3.image.controller
#  swagger-ui:
#    path: swagger-ui.html
spring:
  application:
    name: springboot3-image-service
  profiles:
    active: "common,dev"
  config:
    import: optional:configserver:http://localhost:8800
  cloud:
    config:
      username: goota
      password: 123456

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      #      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8899/eureka}
      defaultZone: http://localhost:8899/eureka